SPORTMEN = [
    "Samuel Arenas", "Valentina Ruiz", "Camilo Martinez",
    "Laura Sanchez", "Andres Gomez", "Mariana Torres",
    "Juan Perez", "Sofia Herrera", "Daniel Morales",
    "Isabella Castro", "Felipe Rivas", "Ana Lucia Delgado",
    "Mateo Cardenas", "Lucia Patino", "Tomas Velasco",
    "Gabriela Lozano", "Sebastian Molina", "Sara Fernandez",
    "Julian Rivera", "Paula Cordoba", "David Andrade",
    "Carolina Bustos", "Santiago Duarte", "Daniela Vargas",
    "Nicolas Ocampo", "Valeria Navarrete", "Esteban Pardo",
    "Manuela Zapata", "Christian Roldan", "Alejandra Montoya",
    "Luis Fernando Ibarra", "Maria Camila Guerra", "Diego Bermudez",
    "Laura Restrepo", "Jorge Armando Suarez", "Natalia Forero",
    "Ricardo Villalba", "Tatiana Aguirre", "Miguel Angel Rojas",
    "Juliana Medina", "Oscar Lemus", "Sara Jaramillo",
    "Hector Lozano", "Adriana Castillo", "Cristian Mejia",
    "Daniela Campos", "Andres Salazar", "Juanita Robledo",
    "Lucia Ramirez", "Diego Munoz", "Camila Pardo",
    "Julian Torres", "Valeria Diaz", "Felipe Castano",
    "Sofia Roldan", "Marco Herrera", "Daniela Silva",
    "Andres Beltran", "Laura Fuentes", "Cristian Arias",
    "Gabriela Correa", "Esteban Molina", "Paula Benavides",
    "Rodrigo Acosta", "Valentina Gutierrez", "Francisco Ledesma",
    "Catalina Espinoza", "Javier Quintero", "Alejandra Suarez",
    "Carlos Mendez", "Florencia Moreno", "Eduardo Guzman",
    "Antonia Palacios", "Gonzalo Rioja", "Daniela Figueroa",
    "Vicente Soto", "Magdalena Torres", "Roberto Zambrano",
    "Claudia Nunez", "Armando Romero", "Beatriz Dominguez",
    "Raul Alarcón", "Francisca García", "Enrique Navarro",
    "Margarita Peña", "Gustavo Medrano", "Isabel Mora",
    "Miguel Ángel Flores", "Rosario Cabrera", "Arturo Valdez",
    "Esperanza López", "Fernando Salas", "Aurelia Vargas",
    "Ernesto Fuerte", "Matilde Serrano", "Aurelio Campos",
    "Herminia Reyes", "Ricardo Brito", "Leonor Pacheco",
    "Oswaldo Riquelme", "Emilia Herrera", "Leopoldo Araya",
    "Eugenia Fuentes", "Pascual Silva", "Oralia Peralta",
    "Rodolfo Rivas", "Estela Pacheco", "Otavio Mendoza",
    "Esmeralda Diaz", "Perfecto Romero", "Oliva Soto",
    "Feliciano Valdés", "Eloisa Campos", "Ovidio Cruz",
    "Emita Monje", "Epifanio Sánchez", "Olimpia Prado",
    "Elida Morales", "Eulogio Benavidez", "Otilia Vega",
    "Elisa Contreras", "Emeterio Arismendi", "Oma Molina",
    "Edith Tapia", "Efrain Mejia", "Obdulia García",
    "Elvira Rojas", "Eladio Cabezas", "Ónix Villegas",
    "Elena Lira", "Electo Herrera", "Olimpo Vásquez",
    "Elba Flores", "Elí Navarro", "Olegario Parra",
    "Elfida Mora", "Elbert Quintana", "Olegaría Castillo",
    "Eleuterio Gómez", "Orleta Riquelme", "Oleida Guzmán",
    "Eliazar Ávila", "Ornela Tapia", "Oleina Acuña",
    "Elbira Mendoza", "Ornelo Araya", "Olegaria Bustos",
    "Eleasar Vega", "Ormanda Espinoza", "Olemira Carrillo",
    "Elicerio Reyes", "Ormey Flores", "Olemia Santos",
    "Elias Toro", "Ormelinda Salinas", "Olerys Velazquez"
]

SPORT = [
    "Futbol", "Baloncesto", "Voleibol", "Tenis", "Natacion", "Atletismo", "Ciclismo",
    "Boxeo", "Rugby", "Beisbol", "Golf", "Taekwondo", "Judo", "Karate", "Esgrima", "Gimnasia Artistica",
    "Levantamiento de Pesas", "Skateboarding", "Surf", "Hockey sobre cesped",
    "Balonmano", "Badminton", "Squash", "Escalada", "Buceo", "Pesas",
    "Arco", "Pentaton Moderno", "Halterofilia", "Lucha Libre", "Billar", "Boliche",
    "Carreras de Caballos", "Automovilismo", "Motociclismo", "Parkour", "Slackline", "Crossfit",
    "Danza Deportiva", "Acrobacias", "Rappel", "Rafting", "Kayak", "Vela",
    "Esqui", "Snowboard", "Patinaje sobre hielo", "Curling"
]

SITES = [
    "Bogota", "Medellin", "Cali", "Barranquilla", "Cartagena",
    "Bucaramanga", "Pereira", "Manizales", "Armenia", "Santa Marta",
    "Cucuta", "Ibague", "Pasto", "Villavicencio", "Monteria",
    "Tunja", "Popayan", "Valledupar", "Sincelejo", "Riohacha",
    "Leticia", "Puerto Caicedo", "Quibdo", "Apartado", "Yopal"
]